package com.revature.post_records;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
@DynamoDBTable( tableName = "records")
public class Records {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String recordId;

    @DynamoDBAttribute
    private List<Player> playerList;

    @DynamoDBAttribute
    private boolean winner;

    @DynamoDBAttribute
    private Date datePlayed;

    @DynamoDBAttribute
    private List<Card> cardList;
}
