package com.revature.post_records;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
@DynamoDBTable( tableName = "records")
public class Records {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String set_id;

    @DynamoDBAttribute
    private String user_id;

    @DynamoDBAttribute
    private boolean win;

    @DynamoDBAttribute
    private Date date_played;

    @DynamoDBAttribute
    private int score;

    @DynamoDBAttribute
    private List<String> card_records;
}
